- name: build and run all nfs
  hosts: test-servers
  become: true
  become_user: root
  gather_facts: true
  vars:
    nfs:
      - cnrnrf-vnf
      - cnrudr
      - cnrudm
      - cnramf
      - cnrsmf
      - cnrausf
      - cnrnssf
      - cnrupf

  tasks:
    - name: copy dockerfile
      copy: src=/home/kaan/Desktop/ulak-staj/Dockerfile dest=/home

    - name: copy build script
      copy: src=/home/kaan/Desktop/ulak-staj/build.sh dest=/home

    - name: build docker images
      command: bash /home/build.sh "{{ item }}"
      loop: "{{ nfs }}"

    - name: run docker images
      command: docker run -it -d --privileged=true "{{ item }}"
      loop: "{{ nfs }}"

    - name: remove build files
      command: rm /home/Dockerfile /home/build.sh 