- hosts: test-servers
  become: true
  become_user: root
  gather_facts: true
  vars:
    nfs:
      - cnrudm

  tasks:
    - name: copy dockerfile
      copy: src=/home/kaan/Desktop/ulak-staj/Dockerfile dest=/home

    - name: copy build script
      copy: src=/home/kaan/Desktop/ulak-staj/build.sh dest=/home

    - name: build docker image
      command: bash /home/build.sh "{{ item }}"
      loop: "{{ nfs }}"

    - name: run docker image
      command: docker run -it -d --privileged=true "{{ item }}"
      loop: "{{ nfs }}"

    - name: remove build files
      command: rm /home/Dockerfile /home/build.sh