- name: build and run all nfs
  hosts: test_servers
  become: true
  become_user: root
  gather_facts: true
  vars:
    nfs:
      - cnramf

  tasks:
    - name: copy dockerfile
      copy: src=/home/kaan/Desktop/ulak-staj/Dockerfile dest=/home

    - name: copy build-run script
      copy: src=/home/kaan/Desktop/ulak-staj/build-run.sh dest=/home

    # may give error if port connection test fails
    - name: build and run docker images
      command: bash /home/build-run.sh "{{ item }}"
      loop: "{{ nfs }}"
      ignore_errors: yes
      no_log: True 

    - name: prepare report
      command: cat /home/report
      register: command

    - name: print report
      debug:
        var: command.stdout_lines

    #- name: remove build files
    #  command: rm /home/Dockerfile /home/build-run.sh /home/build-run-pcf.sh /home/report