- hosts: test-servers
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: copy dockerfile
      copy: src=/home/kaan/Desktop/ulak-staj/Dockerfile dest=/home

    - name: build docker image
      command: docker build -t cnrudm /home

    - name: run docker image
      command: docker run cnrudm